#server:
#  port: 8003
#
#spring:
#  application:
#    name: auth-server
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: admin
#    url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&characterEncoding=UTF-8
#    username: test_user
#
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true # 유레카 서비스에 (자신을) 등록 여부
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    registryFetchIntervalSeconds: 10 # eureka에게 서비스 정보를 가져오는 주기
#    disable-delta: true # eureka에게 서비스 정보를 가져올때 변경된 내용만 가져온다. (false로 하면 전체를 가져오기에 대역폭 낭비이다.
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"